### ISSUE TITLE
As a player I would like to participate in a game-wide chat room.

### ISSUE THREAD

**Issue by mike-eason** [mike-eason/solaris#170]
Will definitely require a big refactor for messaging so could be painful

**Comment by T4G2** [comment]
Maybe it doesnt have to be such a problem. look: when the game start, there will be created room with name of Galaxy Council or so... or do you mean between different games, like in main menu?

**Comment by T4G2** [comment]
If you mena Main Menu chat, i can help you with that if you wants so..

**Comment by mike-eason** [comment]
I've given it some thought and I think the easiest way is to set the `toPlayerId` to `null` for messages sent to a game-wide chat room and then when retrieving messages, only get the messages where the `toPlayerId` is `null`. This will be relatively easy and will allow the implementation of a game-wide chat room without too much effort.

The only issue I can see is how to deal with "unread" messages. To fix that it may be a better idea to instead have a `private` flag on the message which is set to `true` for 1-to-1 conversations and set to `false` for game-wide conversations. This would mean that any messages sent to a game-wide chat room will need to send a message to each player individually in order to track whether messages have been read or not. Not ideal but can't see a way around that.

The big refactor mentioned above stems from the idea of being able to message two or more players privately instead of only being able to have a 1-to-1 conversation with another player. However that is out of scope of this issue.
