### ISSUE TITLE
Usernames and email addresses must not be case sensitive

### ISSUE THREAD

**Issue by mike-eason** [mike-eason/solaris#234]

**Comment by T4G2** [comment]
why? why they should be not case sensitive??

**Comment by mike-eason** [comment]
Problem at the moment is that its possible to create multiple accounts using the same email address, i.e

test@test.com
Test@test.com
TEST@test.com

This should not be allowed. Emails should be case **insensitive**.

The same goes for Usernames, we don't want 2 players sharing the same username but with different casing.
