### ISSUE TITLE
Add black outline to some texts

### ISSUE THREAD

**Issue by T4G2** [mike-eason/solaris#270]
Here's the link how can it be done. (to make contrast better when using player colors as background)
[LINK](https://stackoverflow.com/questions/2570972/css-font-border)

**Comment by mike-eason** [comment]
I couldn't get the font outlines to look very good so instead I added a gradient behind player names:

![image](https://user-images.githubusercontent.com/7103013/91356645-eabdf280-e7e7-11ea-818b-48cebfbc3840.png)
