### ISSUE TITLE
resource score fixed

### ISSUE THREAD

**Issue by T4G2** [mike-eason/solaris#319]
https://github.com/mike-eason/solaris/blob/92ef10b81f6b255df7b00fe5d8326772c94ea660/server/services/random.js#L51

all you need to do to adjust this is change this line to 

`let naturalResources = minResources + (resourceRange * Math.pow(RS_BASE, -RS_EXPONENT * Math.pow(1 - vectorScale, 2)));`

**Comment by mike-eason** [comment]
No longer applicable due to galaxy rework.
