### ISSUE TITLE
Galaxy type and resource distribution on the game settings detail screen does not show friendly text

### ISSUE THREAD

**Issue by mike-eason** [mike-eason/solaris#342]
View detail on a game
- See Galaxy Type
- See Resource Distribution

They are lowercase, they need to be friendly text like the others.

**Comment by William-Schutte** [comment]
Hey! I'm somewhat new to coding and open-source work but I think I've found the issue in the correct view (both in the game and in the code). I can submit a pull request if you'd like!

**Comment by mike-eason** [comment]
Hi @William-Schutte, go ahead, thank you. 👍
