### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by Kurtzmusch** [mike-eason/solaris#348]
there seems to be a memory leak when scrolling the mouse wheel. at first i though it could be related to going in and out of  territory mode, however, it seems that the mere action of scrolling makes memory go up. i though it might just be the lazy GC not working, but even after forcing a garbage collection the memory usage didnt change.

browser: firefox
branch: master (production, solaris.games)

steps to reproduce:
- open a game map
- watch RAM usage closely
- scroll in and out and watch memory rise
- force a garbage collection on the browser( nothing changes )
- close game tab
- force garbage collection again( now memory is freed )

**Comment by mike-eason** [comment]
Likely an issue where the map redraws on zoom end, see `refreshZoom` in `map.js`. We should try commenting out each part one by one to see if it can be isolated.

**Comment by Kurtzmusch** [comment]
it seems the problem is in the drawGarrison... maybe something to do with changing text, since drawing the star names doesnt seem to cause problems

**Comment by Kurtzmusch** [comment]
found the problem, i would say its a library fault, but the workaround is easy.
whenever you set the text object on the a PIXI.Text, a new texture is created by pixi without clearing the previous. the solution is to call destroy() on the Text.texture.
