### ISSUE TITLE
Star sprite is not re-drawn when a carrier launches from a star.

### ISSUE THREAD

**Issue by mike-eason** [mike-eason/solaris#352]
Easiest way to test it is:
- In a turn based game, set a waypoint on a carrier orbiting a star
- When the turn is over and the carrier moves, the star doesn't get drawn, its just an empty circle.
![image](https://user-images.githubusercontent.com/7103013/95751027-e5344300-0c95-11eb-801c-0ade4619a99e.png)

**Comment by Kurtzmusch** [comment]
strange, i cant reproduce

**Comment by Kurtzmusch** [comment]
i've seen it happen a few times now, but i'm not sure how to reproduce, its doesn't always happen

**Comment by mike-eason** [comment]
No longer an issue as carriers are no longer drawn on top of stars.
