### ISSUE TITLE
Console error when clicking on the infrastructure or current research icons on the header.

### ISSUE THREAD

**Issue by mike-eason** [mike-eason/solaris#353]
See screenshot.

![image](https://user-images.githubusercontent.com/7103013/95751351-68559900-0c96-11eb-92ac-b594bd1385b8.png)
![image](https://user-images.githubusercontent.com/7103013/95751372-6f7ca700-0c96-11eb-9f69-06f360a989d1.png)

**Comment by mike-eason** [comment]
@Kurtzmusch was this resolved recently?

**Comment by Kurtzmusch** [comment]
not that i'm aware
