### ISSUE TITLE
Destroy Infrastructure

### ISSUE THREAD

**Issue by Kurtzmusch** [mike-eason/solaris#355]
- Somehow allow player to destroy star infrastructure when facing imminent defeat.
- Should probably be a costly setup.
- Possibly a specialist.
- Should not be something that is quickly and cheaply done whenever the players thinks they'll loose a star.

**Comment by mike-eason** [comment]
Should definitely be a specialist.

Martyr
- Star only
- If the star garrison loses in combat, all infrastructure is destroyed.
- Base cost $500?

**Comment by mike-eason** [comment]
There's now a spec for this.
