### ISSUE TITLE
Map Objects Culling

### ISSUE THREAD

**Issue by Kurtzmusch** [mike-eason/solaris#362]
As map sizes increases, rendering becomes more and more expensive. To keep things smooth, a simple culling algorithm can be implemented, that is: skip drawing elements outside of viewport.

It may not be so relevant now, but for 32 and 64 players games it will surely be necessary, specially on mobile.

For very big maps, the culling itself might become a performance bottleneck, and not worth doing at low zoom levels, and other techniques like chunking might be better.

**Comment by mike-eason** [comment]
@Kurtzmusch is this now resolved?

**Comment by Kurtzmusch** [comment]
yes, i forgot to link on the PR. for bigger maps more work will be done, but i suppose another issue should be created for that.
