### ISSUE TITLE
hard to click on stars that has a close moving carrier when setting waypoints

### ISSUE THREAD

**Issue by Kurtzmusch** [mike-eason/solaris#363]
if there is a carrier very close to a star - no matter whose player it is - it will be very difficult to click on the star when trying to set it as a waypoint destination

**Comment by mike-eason** [comment]
We could ignore the carrier clicked event somehow if the galaxy mode is `waypoints` and the carrier is in transit.

Basically we want to make sure that even if a carrier is clicked and a star is very close the click will *go through* the carrier and click the star instead.

Possibly also increase the star hit radius in waypoints mode too.

**Comment by Kurtzmusch** [comment]
agreed with ignoring clicks on waypoint mode, but i feel like increasing hit radius might be overkill.
