### ISSUE TITLE
cant build infrastructure on captured star

### ISSUE THREAD

**Issue by Kurtzmusch** [mike-eason/solaris#366]
needs a browser refresh to be a able to build on a newly captured star

**Comment by Kurtzmusch** [comment]
might be a duplicate of #228

**Comment by mike-eason** [comment]
Is this still an issue? Need to be able to replicate this with instructions.

**Comment by Kurtzmusch** [comment]
yes, it is.
- send a carrier to star( doesnt matter if its claimed or not, doesnt matter if it has ships defending or not)
- accept your turn
- accept all other players turn
- wait for the server to push back the new state
star is captured but unable to build any structures. curiously, you can still hire specs
