### ISSUE TITLE
As a player I want to see at a glance how my overall empire stats compare to others

### ISSUE THREAD

**Issue by mike-eason** [mike-eason/solaris#419]
- on the player profile page, if the player is looking at their own page it shows green/red values for tech levels.
- green means the player has the highest tech level overall.
- red means the player has the lowest tech level overall.
- we should do the same for the top stats as well like total carriers, stars, new ships etc.

**Comment by naf445** [comment]
Should this still be open? It seems to already be implemented from what I can tell unless I'm misunderstanding something!
