### ISSUE TITLE
As a player I never want to refresh the page.

### ISSUE THREAD

**Issue by mike-eason** [mike-eason/solaris#529]
- Make sure that all game actions are captured and updated via web sockets.
- The end goal is to avoid any "refresh to fix" problems.

**Comment by 0x6273** [comment]
This bug seems to still be present when assigning specialists. I assigned a Space Dock and an Atmosphere Processor, but the ship production and terraformed resources did not change until I F5'd.

**Comment by mike-eason** [comment]
Hi there. Thanks I'll raise this as a separate bug.

The issues list on GitHub hasn't been updated for a while and isn't used often. It's something I've been meaning to get on top of for a while. Most of the tasks are now managed on the discord server.

Thanks.
