### ISSUE TITLE
Battle royale mode

### ISSUE THREAD

**Issue by mike-eason** [mike-eason/solaris#544]
- Every X ticks, the star furthest from the centre goes supernova.
- Last man standing.
- Consider whether to highlight the star that will explode in X ticks.
- Need to consider how to architect the code with new game modes in mind and different win conditions.

**Comment by AntoineCremel** [comment]
Instead of always supernovaing the star furthest from the center, we can imagine a random choice of star, weighted by their distance from the center, to make the game a bit more unpredictable.

**Comment by mike-eason** [comment]
This is now completed, any further enhancements will come as new issues.
