### ISSUE TITLE
Add terrain to galaxies

### ISSUE THREAD

**Issue by mike-eason** [mike-eason/solaris#545]
- Impassable "clouds"?
- Need to be randomly spawned with a random shape and size.
- If a carrier intersects one, it should die.
- Consider whether to prevent players from creating waypoints that intersect them or just let players learn the hard way.

Suggested by The Last Hero.

**Comment by Kurtzmusch** [comment]
ray marching into a 'cloud' made of metaball or simplex noise is easy, but also computationally expensive. another solution is to calculate the intersection of the carrier path with the ellipses that form the cloud, which requires a bit of math skills.
what would those clouds look like on the map?
