### ISSUE TITLE
Rare bug with research

### ISSUE THREAD

**Issue by AntoineCremel** [mike-eason/solaris#551]
- Current research can sometimes be dropped in favor of the next in queue, even though it isn't finished.
- Coincides with Production tick.
- Rare, haven't found a way to reliably reproduce yet.

## Screenshot
![bug-report-solaris](https://user-images.githubusercontent.com/30368294/104853546-db0f8980-5901-11eb-9e7a-8f9d6fbc245d.png)
- Was researching Terraforming, with Weapons cued next. Production tick happens, and Weapons is now the current tech being researched as well as the "next in queue". Terraforming is stopped, with 36 out of 200.

**Comment by mike-eason** [comment]
Could not reproduce this locally.

Here's what happens in the tick:
- Normal research is done
- On production tick, experimentation is performed

Are you sure it isn't that experimentation is done on the technology that you are researching, and it levels up and swaps to the next research?

**Comment by AntoineCremel** [comment]
![image](https://user-images.githubusercontent.com/30368294/104959642-f6969500-59d2-11eb-8635-04fe5b60d75e.png)
On that production tick, experimentation happened on Scanning, and the tech I was researching was terraforming.
