### ISSUE TITLE
Bulk upgrade preview should display/list the chosen stars

### ISSUE THREAD

**Issue by l29ah** [mike-eason/solaris#569]
As it may make stupid decisions, like buying a research lab on a star that's going to be lost to an enemy soon.

**Comment by mike-eason** [comment]
Hi @l29ah,

This is now released. Enjoy!

**Comment by l29ah** [comment]
There's some inconsistency in the preview: 
![screenshot-inconsistent](https://user-images.githubusercontent.com/31852/106356473-e0f96780-6310-11eb-82c0-54cf65c398b3.png)

**Comment by l29ah** [comment]
Also it fails to find some cheaper opportunities for upgrades.

**Comment by mike-eason** [comment]
Re-opening this issue.

**Comment by mike-eason** [comment]
@l29ah I see the issue. The cost being displayed on the UI is the *next* infrastructure cost (how much it costs to upgrade again) instead of the total cost of the bulk upgrade.

My bad, will release a fix later.
