### ISSUE TITLE
Multiple conversation with the same recipients

### ISSUE THREAD

**Issue by Ownezx** [mike-eason/solaris#677]
As alliance with many members form it is hard to distinguish the important information from the general discussion.

I would love to be able to have two conversations called "Alliance" and "[IMPORTANT] Alliance" for people to be able to not have to filter through the messages to find important information.

Current behaviour:
When we attempt to create a conversation with the same participants, we get the error "A conversation already exists with the selected participants named CONVERSATION NAME."

Proposed behaviour:
We check if a conversations with the same name. If the name is unique then create the conversation.

Alternate prosposed behaviour:
Be able to pin messages that are important and being able to show only pinned message. All participant in the conversation can pin and unpin message.

**Comment by mike-eason** [comment]
Best of both worlds: A warning pops up before you create the conversation but doesn't prevent you from creating a *duplicate* chat. 👍

**Comment by Ownezx** [comment]
Just a thought, since clicking message on someone you already have a conversation with takes you to that conversation we might have to either
 - Not allow to create multiple conversation with a single player
 - Change the behaviour of that button when there is multiple conversations

**Comment by mike-eason** [comment]
Very good point @Ownezx. For this reason I implemented the ability to pin messages.
