### ISSUE TITLE
Improve visibility for voronoi territory style for same colored faction

### ISSUE THREAD

**Issue by Ownezx** [mike-eason/solaris#678]
When in a 32v game, looking at territories using the marching square is very clear as the territory is in a uniform color and the border in a deeper thick line. 

Issue: When using the Voroi territory style, each cell has identical vertex style. This makes it hard to see where the frontier is between two faction of identical color.

Proposed solution: Use a similar render method as the marching square style where only the vertexes at the border of a territory is drawn.

**Comment by ScorpioneOrzion** [comment]
Would allow you to see who has what better I guess

**Comment by mike-eason** [comment]
While it is a nice to have it will involve a lot of work due to the current implementation of the Voronoi map not really having any notion of borders, considering this a super low priority.

**Comment by mike-eason** [comment]
It turns out that @Kurtzmusch and @ScorpioneOrzion are geniuses and have resolved this issue. 🤝
