### ISSUE TITLE
Symmetric/mirrored galaxy mode

### ISSUE THREAD

**Issue by mike-eason** [mike-eason/solaris#83]
Suggested by BelSon.

Particularly important for 1v1s.

Create 1 half of a galaxy and mirror it on the other side, should be pretty straightforward star generation.

**Comment by mike-eason** [comment]
> This galaxy is set up by creating the star field for one player, then mirroring it along a straight line. This could possibly be generalised to allow for more than two players, such as filling out a pizza wedge and then rotating that wedge so that everyone has identical wedges, or some other variation.

**Comment by Kurtzmusch** [comment]
this seems easy... should the resources be symetrical too? should it be perfectly simetrical or just ensuring a similar shape, number of stars and resources?

**Comment by mike-eason** [comment]
Yes, I think it should be completely symmetrical, resources and all.
